version: '3.8'
services:
  db:
    image: postgres:14
    container_name: school_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_mgmt
    ports:
      - "5432:5432"
    volumes:
      - ./seed_db:/docker-entrypoint-initdb.d